config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :homepages
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'homepages#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/homepage.rb
class Homepage < ApplicationRecord
    has_one_attached :video
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :avatar
    has_many_attached :images1
    has_many_attached :images2
    validates :name, :description ,:classify ,:color1, :size1 ,:price1 ,:avatar ,:presence => true
    validates :price1, :numericality => {:greater_than_or_equal_to => 100000}
    validates :name,:uniqueness => true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
    def current_cart
        Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
        cart = Cart.create
        session[:cart_id] = cart.id
        cart
    end
    
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :set_homepage, only: %i[ show edit update destroy ]

  # GET /homepages or /homepages.json
  def index
    @homepages = Homepage.all
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
    @latest = Product.where('classify = "Latest"').find_each
    @greatest = Product.where('classify = "Greatest"').find_each
  end

  # GET /homepages/1 or /homepages/1.json
  def show
  end

  # GET /homepages/new
  def new
    @homepage = Homepage.new
  end

  # GET /homepages/1/edit
  def edit
  end

  # POST /homepages or /homepages.json
  def create
    @homepage = Homepage.new(homepage_params)

    respond_to do |format|
      if @homepage.save
        format.html { redirect_to homepage_url(@homepage), notice: "Homepage was successfully created." }
        format.json { render :show, status: :created, location: @homepage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homepages/1 or /homepages/1.json
  def update
    respond_to do |format|
      if @homepage.update(homepage_params)
        format.html { redirect_to homepage_url(@homepage), notice: "Homepage was successfully updated." }
        format.json { render :show, status: :ok, location: @homepage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homepages/1 or /homepages/1.json
  def destroy
    @homepage.destroy

    respond_to do |format|
      format.html { redirect_to homepages_url, notice: "Homepage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homepage
      @homepage = Homepage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def homepage_params
      params.require(:homepage).permit(:video)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
  end

  # GET /products/1 or /products/1.json
  def show
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :avatar, :size1, :size2, :color1, :color2, :price1 ,:price2, :classify, :description, images1:[] ,images2:[] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/homepages/_form.html.erb
<body class="homepageform">



<%= form_with(model: homepage) do |form| %>
  <% if homepage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(homepage.errors.count, "error") %> prohibited this homepage from being saved:</h2>

      <ul>
        <% homepage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
  <p>Video for homepage:</p>
  <video muted autoplay controls loop %>" >
    <source src="<%= url_for(homepage.video)%>" type="video/mp4" />
  </video>
  </div>

  <div>
    <p>Change video for homepage:</p>
    <%= form.file_field :video %>
  </div>


  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>



</body>

app/views/homepages/_homepage.html.erb
<div id="<%= dom_id homepage %>">
</div>

app/views/homepages/edit.html.erb
<div id="form">

<h1>Editing homepage</h1>
<br>
<%= render "form", homepage: @homepage %>

</div>

app/views/homepages/index.html.erb
<%= render "layouts/header" %>
<body class="homepageindex">
  <div class="normal">

    <h1><%= link_to "Nabi la robe", products_path, class:"nav-link" %></h1>

      <% @homepages.each do |homepage| %>
        <% if admin_signed_in? %>
          <%= link_to "Edit Video", edit_homepage_path(homepage) %>
        <%end%>

        <% if homepage.video.attached? %>
          <video muted autoplay controls loop %>" >
            <source src="<%= url_for(homepage.video)%>" type="video/mp4" />
          </video>
        <% end %>
      <% end %>

          
    <!-- carousel --> 
    <div class="homepage1">  
      <div class="flex">
        <div>
          <%= search_form_for @q do |find| %>
            <button id="find_submit" type="submit" class="btn" ><span class="title">Latest</span></button>
            <%= find.hidden_field :classify_cont, value: "Latest" ,class:"form-control" %> 
          <% end %>
        </div>

        <% @products.take(1).each do |product| %> <!--##dung take(1) hoac slice(1,1)-->
          <div id="carousel1_<%= product.id %>" class="carousel slide" data-bs-ride="carousel" >

            <div class="carousel-inner">
              <% @latest.each_with_index do |product, index| %>
                <div id="carousel_item_<%= index %>" class="carousel-item <%= index == 0 ? 'active' : '' %>">
                  <%= link_to image_tag(product.avatar, :class => 'image'),product %><br>
                    <div class="carousel-caption"><h4><%=product.name%></h4>     <!-- carousel-caption de chu nam trong hinh --> 
                      <h3><%=number_to_currency product.price1/25000-0.01%></h3>
                    </div>
                </div>
              <% end %>
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carousel1_<%= product.id %>" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel1_<%= product.id %>" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>   
          </div>
        <% end %>
      </div>
    </div>

    <div class="homepage2">  
    <div class="flex">
      <div>
        <%= search_form_for @q do |find| %>
          <button id="find_submit" type="submit" class="btn" ><span class="title">Greatest</span></button>
          <%= find.hidden_field :classify_cont, value: "Greatest" ,class:"form-control" %> 
        <% end %>
      </div>

      <% @products.take(1).each do |product| %> <!--##dung take(1) hoac slice(1,1)-->
        <div id="carousel2_<%= product.id %>" class="carousel slide" data-bs-ride="carousel" >

          <div class="carousel-inner">
            <% @greatest.each_with_index do |product, index| %>
              <div id="carousel_item_<%= index %>" class="carousel-item <%= index == 0 ? 'active' : '' %>">
                <%= link_to image_tag(product.avatar, :class => 'image'),product %><br>
                  <div class="carousel-caption"><h4><%=product.name%></h4>     <!-- carousel-caption de chu nam trong hinh --> 
                    <h3><%=number_to_currency product.price1/25000-0.01%></h3>
                  </div>
              </div>
            <% end %>
          </div>

          <button class="carousel-control-prev" type="button" data-bs-target="#carousel2_<%= product.id %>" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carousel2_<%= product.id %>" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>   
        </div>
      <% end %>
    </div>
  </div>
  <p>.</p>
</body>
<%= render "layouts/footer" %>

app/views/homepages/new.html.erb
<h1>New homepage</h1>

<%= render "form", homepage: @homepage %>

<br>

<div>
  <%= link_to "Back to homepages", homepages_path %>
</div>

app/views/homepages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @homepage %>

<div>
  <%= link_to "Edit this homepage", edit_homepage_path(@homepage) %> |
  <%= link_to "Back to homepages", homepages_path %>

  <%= button_to "Destroy this homepage", @homepage, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="grid-container editfooter sticky-bottom">
    <div class="grid-item">About Nabi</div>
    <div class="grid-item">Contact Us</div>
    <div class="grid-item">Order Status</div>  
    <div class="grid-item">Find Our Store</div>
    <div class="grid-item">Send Feedback</div>  
    <div class="grid-item">Legal</div>
    
    <div class="item2">&#9743; 0934114954-VietNam 2021-2022 Nabi la robe® - All rights reserved. </div  >
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm bg-black"> 
    <%= link_to image_tag('nabi4.jpg',:class => 'rounded-pill'),root_path,class:"navbar-brand" %>
    
    <ul class="navbar-nav me-auto ">
      <li >
        <%= link_to "All Dresses", products_path, class:"nav-link"  %>
      </li>

      <li class="dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Find Us On</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" style="color:rgb(184, 138, 230);" target="_blank" href="https://www.instagram.com/nabi.larobe/">Instagram</a></li>
            <li><a class="dropdown-item" style="color:rgb(184, 138, 230);" target="_blank" href="https://www.facebook.com/nabilarobee">Facebook</a></li>
            <li><a class="dropdown-item" style="color:rgb(184, 138, 230);" target="_blank" href="https://shopee.vn/nabilarobe"> Shopee</a></li>
            <li><a class="dropdown-item" style="color:rgb(184, 138, 230);" target="_blank" href="https://www.tiktok.com/@nabilarobe"> Tiktok</a></li>
          </ul>
      </li>

      <% if admin_signed_in? %>
        <li class="nav-item" >
          <%= link_to "Edit Profile", edit_admin_registration_path, class:"nav-link"  %>
        </li>
        <li class="nav-item" >
          <%= link_to 'New Product', new_product_path , class:"nav-link"  %>
        </li>

        <%= button_to "Sign Out",  destroy_admin_session_path,:method => :delete, class:"btn btn-default nav-link"  %>
                          <!-- khong duoc de nav-item ,khong bam duoc ,phai de button_to -->
      <% else %>
        <li class="nav-item" >
          <%= link_to "Admin Log in", new_admin_session_path, class:"nav-link"  %>
        </li>
      <% end %>
    </ul> 
    

      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "search .jpg"  ,class:"search rounded-pill" %>
        <%= find.search_field :name_or_classify_or_color1_or_color2_or_size1_or_size2_cont , placeholder:"What are you looking for ? (name,color,...)",list:"datalistOptions",class:"search2 form-control",id:"find"%> 
    
          <datalist id="datalistOptions">
            <option value="Latest" >
            <option value="Greatest">
            <option value="Pink">
            <option value="White">
            <option value="Red">
            <option value="Freesize">
          </datalist>
      <% end %>

   
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= favicon_link_tag 'brand.png'  %>
    <title>Nabilarobe Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>  

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>

  <div>
    <%= yield %>
  </div>

  </body>

</html>

app/views/products/_filter.html.erb
<!-- (button id="find_submit") = f.submit -->


<h2>Sort</h2>
  <li ><%= sort_link(@q, :name ,"Sort by Name",class:"col1") %></li>
  <li ><%= sort_link(@q, :price1 ,"Sort by Price",class:"col1")%></li>
<br>

<h2> Filter </h2>
  <li><a class="col1" data-bs-toggle="collapse" href="#collapse1" >Classify</a></li>
    <div class="collapse show" id="collapse1">
      <%= search_form_for @q do |find| %>
        <button id="find_submit" class="btn btn-default" ><span class="col2">Latest</span></button>
          <%= find.hidden_field :classify_cont, value: "Latest" %>
      <%end%>

      <%= search_form_for @q do |find| %>
        <button id="find_submit" class="btn btn-default" ><span class="col2">Greatest</span></button>
          <%= find.hidden_field :classify_cont, value: "Greatest" %>
      <%end%>
    </div>

  <li><a class="col1" data-bs-toggle="collapse" href="#collapse2" >Size</a></li>
    <div class="collapse show" id="collapse2">
      <%= search_form_for @q do |find| %>
        <button id="find_submit" class="btn btn-default" ><span class="col2">Freesize</span></button>
          <%= find.hidden_field :size1_or_size2_cont, value: "Freesize" %>
      <%end%>

      <%= search_form_for @q do |find| %>
        <button id="find_submit" class="btn btn-default" ><span class="col2">S</span></button>
          <%= find.hidden_field :size1_or_size2_start, value: "S" %>
      <%end%>

      <%= search_form_for @q do |find| %>
        <button id="find_submit" class="btn btn-default" ><span class="col2">M</span></button>
          <%= find.hidden_field :size1_or_size2_cont, value: "M" %>
      <%end%>
    </div>

  <li><a class="col1" data-bs-toggle="collapse" href="#collapse3" >Color</a></li>
    <div class="collapse show" id="collapse3">
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "white.png"  ,class:"colorround rounded-pill" %> White
      <%= find.hidden_field :color1_or_color2_cont, value: "White" %> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "blackandwhite.png"  ,class:"colorround rounded-pill" %> Black and White
      <%= find.hidden_field :color1_or_color2_cont, value: "Black and White" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "black.jpg"  ,class:"colorround rounded-pill" %> Dark
      <%= find.hidden_field :color1_or_color2_cont, value: "Black" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "brown.png"  ,class:"colorround rounded-pill" %> Brown
      <%= find.hidden_field :color1_or_color2_cont, value: "Brown" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "lightbrown.png"  ,class:"colorround rounded-pill" %> Light Brown
      <%= find.hidden_field :color1_or_color2_cont, value: "Light Brown" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "pink.png"  ,class:"colorround rounded-pill" %> Pink
      <%= find.hidden_field :color1_or_color2_cont, value: "Pink" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "deeppink.png"  ,class:"colorround rounded-pill" %> Deep Pink
      <%= find.hidden_field :color1_or_color2_cont, value: "Deep Pink" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "champagepink.jpeg"  ,class:"colorround rounded-pill" %> Champage Pink
      <%= find.hidden_field :color1_or_color2_cont, value: "Champage Pink" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "red.jpeg"  ,class:"colorround rounded-pill" %> Red
      <%= find.hidden_field :color1_or_color2_cont, value: "Red" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "violet.png"  ,class:"colorround rounded-pill" %> Violet
      <%= find.hidden_field :color1_or_color2_cont, value: "Violet" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "cream.png"  ,class:"colorround rounded-pill" %> Cream
      <%= find.hidden_field :color1_or_color2_cont, value: "Cream" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "blue.png"  ,class:"colorround rounded-pill" %> Cyan
      <%= find.hidden_field :color1_or_color2_cont, value: "Cyan" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "darkblue.png"  ,class:"colorround rounded-pill" %> Dark Blue
      <%= find.hidden_field :color1_or_color2_cont, value: "Dark Blue" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "chocolate.jpg"  ,class:"colorround rounded-pill" %> Chocolate
      <%= find.hidden_field :color1_or_color2_cont, value: "Chocolate" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "green.png"  ,class:"colorround rounded-pill" %> Green
      <%= find.hidden_field :color1_or_color2_cont, value: "Green" ,class:"form-control",id:"find"%> 
      <% end %>
      <%= search_form_for @q do |find| %>
        <input id="find_submit" type="image" <%= image_tag "darkgreen.png"  ,class:"colorround rounded-pill" %> Dark Green
      <%= find.hidden_field :color1_or_color2_cont, value: "Dark Green" ,class:"form-control",id:"find"%> 
      <% end %>
    </div>

app/views/products/_form.html.erb
<body class="productform">
  
  <%= form_with(model: product) do |form| %>
    <% if product.errors.any? %>
      <div style="color:red">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div>
    <%= form.label :name ,style: "display: block"%>
    <%= form.text_field :name %>
  </div><br>
  
  <div>
    <%= form.label :classify ,style: "display: block"%>
    <%= form.select :classify, ['Latest', 'Greatest', 'None'] ,class:"input2" %>
  </div><br>
    
 <div>
    <%= form.label :avatar ,style: "display: block" %>
    <%= form.file_field :avatar %>
  </div>
  <% if @product.avatar.attached? %>
    <%= image_tag @product.avatar ,class:"image" %><br>
  <% end %><br>
  <div>
    <%= form.label :description ,style: "display: block"%>
    <%= form.text_area :description, class:"input1" %>
  </div>
  <div class="form1">
    <div>
      <%= form.label :color1, style: "display: block" %>
      <%= form.text_field :color1 %>
    </div><br>
    
    <div>
      <%= form.label :price1, style: "display: block" %>
      <%= form.text_field :price1 %>
    </div><br>
    
    <div>
      <%= form.label :size1, style: "display: block" %>
      <%= form.text_field :size1 ,class:"input3"%>
    </div><br>

    <div>
      <%= form.label :images1 %>
      <%= form.file_field :images1, multiple: true ,style: "display: block"  %>
      <% @product.images1.each do |image| %>
        <%= image_tag image ,class:"image" %>
      <%end%>
    </div><br>

    <div>
    <%= form.submit %>
    </div>
  </div>

  <div class="form2">

    <div>
      <%= form.label :color2, style: "display: block" %>
      <%= form.text_field :color2 %><br>
    </div><br>
    
    <div>
      <%= form.label :price2, style: "display: block" %>
      <%= form.text_field :price2 %>
    </div><br>
    
    <div>
      <%= form.label :size2, style: "display: block" %>
      <%= form.text_field :size2 ,class:"input3"%>
    </div><br>  

    <div>
    <%= form.label :images1 %>
    <%= form.file_field :images2, multiple: true ,style: "display: block"  %>
    <% @product.images2.each do |image| %>
      <%= image_tag image ,class:"image" %>
    <%end%>
  </div>
  
  </div><br>

  <% end %>

</body>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" >
</div>

app/views/products/edit.html.erb
<div id="form">
<h1>Editing product</h1>

<%= render "form", product: @product %>



<div class="edit">
  <%= link_to "Show", @product ,class:"btn btn-info  me-3 "%> |
  <%= link_to "Back", products_path ,class:"btn btn-info  ms-3 "%> 
  <br>
  <%= button_to 'Destroy', @product, data: { confirm: 'Are you sure?' }, :method => :delete ,class:"btn btn-danger mt-3 me-3"%>
</div>
</div>

app/views/products/index.html.erb
<%= render "layouts/header" %>
<body class="productindex">
  <p style="color: green"><%= notice %></p>
  <p style="color: green"><%= alert %></p>
  <div class="normal">
  <h1><%= link_to "All Nabi Dresses", products_path, class:"nav-link" %></h1>
  <div class="filter">
  <%= render "filter" %>
  </div>
  <div class="allproduct">
    <% @products.each do |product| %>
    
      <% render product %>  <!-- #add = for connect to _product.hmtl.erb ,not reccommend-->

      <div class="eachproduct">
        <% if admin_signed_in? %>      
          <div>
            <%= link_to "Edit", edit_product_path(product) ,class:'edit'%> 
          </div>
        <%end%>

        <div>
          <%= link_to image_tag(product.avatar,class:'image'),product %>
        </div>

        <div class="price">
          <%= number_to_currency (product.price1/25000)-0.01  %>
          <%if product.price2.present? %>~
            <%= number_to_currency (product.price2/25000)-0.01  %>
          <%end%>
        </div>

        <div class="name">
          <%= product.name %>
        </div>

        <div class="size">
          <%= product.size1 %>
          <%if product.size2.present? %>-
          <%= product.size2 %>
          <%end%>
        </div>
        
        <div class="color">
          <%= product.color1 %>
          <%if product.color2.present? %>/
            <%= product.color2 %>
          <%end%>
        </div>

      </div>
    <% end %>
  </div>
  </div>
</body>
<%= render "layouts/footer" %>

app/views/products/new.html.erb
<div id="form">
<h1>New product</h1>

<%= render "form", product: @product %>
</div>